version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '3002:3002'
    volumes:
      - /app/backend
      - /app/node_modules
  youtubeapi:
    build: ./server
    container_name: youtubeapi_calls
    ports:
      - '3001:3001'
    volumes:
      - /app/server # 
      - /app/node_modules # Preserves the node_modules directory in the container
  client:
    build: ./musicmirror
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/musicmirror
      - /app/node_modules
    stdin_open: true
    tty: true