version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '5000:5000'
    volumes:
      - /app/backend
      - /app/node_modules

  client:
    build: ./musicmirror
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/musicmirror
      - /app/node_modules
    stdin_open: true
    tty: true